Repository Yeonu-Kim/snutt_clone_7, pull requests merged in 2024-10, with the labels that each got.

#2 [FEAT] api 연결을 위한 설정 및 스켈레톤 코드 작성
  src/App.tsx
  src/api/apis/api.ts
  src/api/apis/index.ts
  src/api/apis/schemas.ts
  src/api/apis/types.ts
  src/api/index.ts
  src/api/response.ts
  src/context/EnvContext.ts
  src/context/ServiceContext.ts
  src/entities/auth.ts
  src/entities/error.ts
  src/entities/response.ts
  src/entities/user.ts
  src/hooks/useGaurdContext.ts
  src/infrastructure/impleAuthRepository.ts
  src/infrastructure/impleUserRepository.ts
  src/main.tsx
  src/pages/landing/index.tsx
  src/usecases/authServices.ts
  src/usecases/userService.ts
Labels: enhancement

#11 Style/#7/goranikin
  package.json
  public/TimeTable.png
  public/appleid.png
  public/facebookid.png
  public/googleid.png
  public/kakaotalkid.png
  public/status-icon.png
  src/main.tsx
  src/pages/landing/index.tsx
  yarn.lock
Labels: question

#9 [FEAT] 유저 state에 따른 redirect
  index.html
  package.json
  public/favicon.ico
  src/App.tsx
  src/context/TokenManageContext.ts
  src/hooks/useGuardContext.ts
  src/infrastructure/impleStorageRepository.ts
  src/main.tsx
  src/pages/login/index.tsx
  src/usecases/tokenService.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement

#15 [FIX] 라우터 및 auth state 네이밍 수정
  public/landing/appleid.png
  public/landing/facebookid.png
  public/landing/googleid.png
  public/landing/kakaotalkid.png
  public/logo/TimeTable.png
  public/status-icon.png
  src/App.tsx
  src/components/Auth.tsx
  src/constants/route.ts
  src/context/TokenAuthContext.ts
  src/pages/Landing/index.tsx
Labels: refactor

#18 [REFACTOR] tokenService -> authService로 통합
  src/App.tsx
  src/infrastructure/impleAuthRepository.ts
  src/infrastructure/impleStorageRepository.ts
  src/infrastructure/impleUserRepository.ts
  src/usecases/authServices.ts
  src/usecases/tokenService.ts
  src/usecases/userService.ts
Labels: refactor

#22 [FIX] 토큰 만료 시 재로그인 완료되면 모달창 닫히기
  src/App.tsx
  src/components/Auth.tsx
  src/context/ModalManageContext.ts
  src/context/TokenAuthContext.ts
  src/context/TokenManageContext.ts
  src/pages/Main/index.tsx
  src/pages/SignIn/index.tsx
  src/usecases/authServices.ts
Labels: bug

#25 [FEAT] 메인페이지 스타일링
  src/api/apis/api.ts
  src/entities/user.ts
  src/pages/Main/index.tsx
  src/usecases/userService.ts
Labels: style

#27 [STYLE] 로딩 페이지 스타일링
  src/components/Loading.tsx
  src/pages/Main/index.tsx
  tailwind.config.js
Labels: style

#30 [FEAT] 로그인 페이지에 로딩창 추가
  src/pages/SignIn/index.tsx
Labels: enhancement

#31 [FEAT] 모달 팝업 스타일링
  src/components/Modal.tsx
  tailwind.config.js
Labels: style

#32 [STYLE] Button Hover 구현
  src/pages/Landing/index.tsx
  src/pages/SignIn/index.tsx
Labels: style

#33 [FEAT] 토스트 적용
  package.json
  src/App.tsx
  src/pages/Main/index.tsx
  src/pages/SignIn/index.tsx
  yarn.lock
Labels: enhancement

#38 useNavigate custom hook 구현 #34
  src/hooks/useNavigation.ts
  src/pages/Landing/index.tsx
Labels: enhancement

#36 [FEAT] 로딩페이지에서 랜덤으로 팁이 나오도록 수정
  src/components/Loading.tsx
Labels: bug

#42 [STYLE] 전체 공통 레이아웃 생성
  README.md
  index.html
  src/components/styles/Layout.tsx
  src/index.css
  src/pages/Landing/index.tsx
  src/pages/Main/index.tsx
  src/pages/SignIn/index.tsx
  tailwind.config.js
Labels: style

#43 [FEAT] 로그아웃 기능 추가
  src/pages/Landing/index.tsx
  src/pages/Main/index.tsx
Labels: enhancement

#47 [STYLE] 로그인 버튼 최하단에 위치하도록 변경
  src/pages/SignIn/index.tsx
Labels: style

#48 [STYLE] 메인 페이지 100dvh 넘지 않도록 수정
  public/logo/TimeTable.png
  public/logo/snutt_logo.svg
  src/components/styles/Layout.tsx
  src/index.css
  src/pages/Landing/index.tsx
  tailwind.config.js
Labels: style

#40 [FEAT] 로그인 페이지 뒤로 버튼 기능 구현
  src/hooks/useNavigation.ts
  src/pages/SignIn/index.tsx
Labels: enhancement

#58 [style] 공통 button 만들기
  src/components/styles/Button.tsx
  src/pages/Error/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Main/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  tailwind.config.js
Labels: refactor

#55 [FIX] vercel rewrite 설정
  vercel.json
Labels: bug, major

#56 [FIX] # 링크 사용 시 페이지 전환 안되는 문제 해결
  src/hooks/useNavigation.ts
  src/pages/SignIn/index.tsx
Labels: bug, major

#60 [REFACTOR] toast alarm을 관리하는 util function 생성
  src/App.tsx
  src/pages/Main/index.tsx
  src/pages/SignIn/index.tsx
  src/utils/showDialog.ts
Labels: refactor

#62 [REFACTOR] useNavigation return 방식 변경
  src/hooks/useNavigation.ts
Labels: refactor

#64 [FEAT] 네비바 생성
  public/navbar/tab_ev_off.svg
  public/navbar/tab_friends_off.svg
  public/navbar/tab_mypage_off.svg
  public/navbar/tab_mypage_on.svg
  public/navbar/tab_search_off.svg
  public/navbar/tab_search_on.svg
  public/navbar/tab_timetable_off.svg
  public/navbar/tab_timetable_on.svg
  src/App.tsx
  src/components/Navbar.tsx
  src/components/styles/Layout.tsx
  src/constants/fileSource.ts
  src/constants/route.ts
  src/hooks/useNavigation.ts
  src/pages/Main/index.tsx
  src/pages/MyPage/index.tsx
Labels: feature

#69 [REFACTOR] 절대경로로 수정
  src/App.tsx
  src/components/Auth.tsx
  src/components/Navbar.tsx
  src/context/ServiceContext.ts
  src/context/TokenManageContext.ts
  src/infrastructure/impleAuthRepository.ts
  src/infrastructure/impleStorageRepository.ts
  src/infrastructure/impleUserRepository.ts
  src/main.tsx
  src/pages/Error/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/usecases/authServices.ts
  tsconfig.json
  vite.config.ts
Labels: refactor

#57 [FIX] 재로그인을 실행할 때 무효 토큰 삭제 및 로그아웃
  src/App.tsx
  src/components/Auth.tsx
  src/components/Modal.tsx
  src/constants/route.ts
  src/context/ModalManageContext.ts
  src/context/TokenAuthContext.ts
  src/pages/Main/index.tsx
  src/pages/SignIn/index.tsx
Labels: bug, minor

#72 [FIX] placeholder 폰트 크기 통일 및 불필요한 폰트 삭제
  src/pages/SignIn/index.tsx
  tailwind.config.js
Labels: bug

#75 [FEAT] 메인페이지 구조 생성
  src/pages/Main/drawer/index.tsx
  src/pages/Main/index.tsx
  src/pages/Main/timeTable/index.tsx
  src/pages/MyPage/index.tsx
Labels: feature

#79 [REFACTOR] useNavigation -> useRouteNavigation 변경
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/hooks/useRouteNavigation.ts
  src/pages/Landing/index.tsx
  src/pages/SignIn/index.tsx
Labels: refactor

#83 [REFACTOR] tsx, css 스타일 지식 중복 제거
  src/App.tsx
  src/components/styles/ChangeNicknamePTag.tsx
  src/components/styles/WhiteButtonBox.tsx
  src/pages/MyPage/Account/ChangeNickname/index.tsx
  src/pages/MyPage/Account/index.tsx
  src/pages/MyPage/index.tsx
Labels: refactor

#77 [STYLE] 서랍 스타일링
  public/arrow/arrow_down.svg
  public/header/hamburger.svg
  src/components/styles/Layout.tsx
  src/constants/fileSource.ts
  src/pages/Main/Drawer/AddTimeTableBottonSheet.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/ChangeNameDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/DeleteDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/pages/Main/Drawer/index.tsx
  src/pages/Main/Header/index.tsx
  src/pages/Main/TimeTable/index.tsx
  src/pages/Main/drawer/index.tsx
  src/pages/Main/index.tsx
  src/pages/Main/timeTable/index.tsx
  src/utils/format.ts
  tailwind.config.js
Labels: style

#87 [STYLE] 토스터 위치 변경
  src/App.tsx
Labels: style

#89 [FIX] api 공통 error response 추가
  src/api/apis/api.ts
  src/api/apis/index.ts
  src/api/response.ts
Labels: bug

#94 [FIX] 서랍 시간표 정렬 기준 변경
  src/pages/Main/Drawer/index.tsx
  src/pages/Main/index.tsx
Labels: bug, style

#95 [FEAT] 서랍 api 연결
  src/App.tsx
  src/api/apis/api.ts
  src/api/apis/schemas.ts
  src/context/ServiceContext.ts
  src/entities/courseBook.ts
  src/entities/timetable.ts
  src/infrastructure/impleCourseBookRepository.ts
  src/infrastructure/impleTimeTableRespository.ts
  src/pages/Main/Drawer/AddTimeTableBottomSheet/index.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/ChangeNameDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/DeleteDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/pages/Main/Drawer/index.tsx
  src/usecases/courseBookService.ts
  src/usecases/timeTableService.ts
Labels: feature
