Repository Yeonu-Kim/snutt_clone_7, pull requests merged in 2024-11, with the labels that each got.

#99 [FIX] 서랍 열렸을 때 max-h 제한 삭제
  src/pages/Main/Drawer/index.tsx
Labels: bug, style

#101 [REFACTOR] 서랍 공통 컴포넌트 및 커스텀 훅 생성
  src/components/Auth.tsx
  src/components/BottomeSheetContainer.tsx
  src/components/Dialog.tsx
  src/components/DrawerContainer.tsx
  src/hooks/useVisible.ts
  src/pages/Main/Drawer/AddTimeTableBottomSheet/index.tsx
  src/pages/Main/Drawer/AddTimeTableBySemesterBottomSheet/index.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/ChangeNameDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/DeleteDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/pages/Main/Drawer/index.tsx
  src/usecases/timeTableService.ts
  tailwind.config.js
Labels: refactor

#91 [FEAT] 닉네임 변경 기능 만들기
  src/App.tsx
  src/api/apis/api.ts
  src/api/apis/schemas.ts
  src/constants/route.ts
  src/hooks/useRouteNavigation.ts
  src/infrastructure/impleUserRepository.ts
  src/pages/MyPage/Account/ChangeNickname/index.tsx
  src/pages/MyPage/Account/index.tsx
  src/pages/MyPage/index.tsx
  src/usecases/userService.ts
Labels: feature

#103 [REFACTOR] ChangeNickname index.tsx 수정
  src/pages/MyPage/Account/ChangeNickname/index.tsx
Labels: refactor

#111 [FEAT] 아이콘 생성
  package.json
  src/components/Drawer.tsx
  src/pages/Main/Drawer/index.tsx
  src/pages/SignIn/index.tsx
  yarn.lock
Labels: style

#120 [STYLE] Remix Icon 라이브러리 삭제 및 SVG 파일로 대체
  package.json
  public/drawer/Add.svg
  public/drawer/CheckBoxCircle.svg
  public/drawer/Close.svg
  public/drawer/Copy.svg
  public/drawer/More.svg
  public/drawer/Primary.svg
  public/navbar/tab_friends_on.svg
  src/components/Drawer.tsx
  src/constants/fileSource.ts
  src/pages/Main/Drawer/index.tsx
  src/pages/SignIn/index.tsx
  yarn.lock
Labels: style

#122 [REFACTOR] Drawer 관련 컴포넌트는 Drawer에 위치하도록 수정
  src/components/Drawer.tsx
  src/pages/Main/Drawer/index.tsx
Labels: refactor

#123 [FEAT] 스피너 로딩 추가
  public/drawer/User.svg
  src/components/Loading.tsx
  src/pages/Main/Drawer/AddTimeTableBottomSheet/index.tsx
  src/pages/Main/Drawer/AddTimeTableBySemesterBottomSheet/index.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/ChangeNameDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/DeleteDialog.tsx
  src/pages/MyPage/Account/ChangeNickname/index.tsx
Labels: feature

#132 [STYLE] mypage 좀 더 예쁘게 만들어보기
  src/pages/MyPage/Account/index.tsx
  src/pages/MyPage/index.tsx
  tsconfig.tsbuildinfo
Labels: style

#133 [FEATURE] mypage 닉네임 복사 기능 추가
  src/pages/MyPage/Account/index.tsx
Labels: feature

#137 [FIX] tsconfig.tsbuild 파일 없애기
  .gitignore
Labels: bug

#139 [FIX] tsconfig.tsbuild 파일 없애기 (Re)
  tsconfig.tsbuildinfo
Labels: bug

#141 [REFACTOR] path의 root 구조 변경
  src/App.tsx
  src/components/Navbar.tsx
  src/constants/route.ts
  src/hooks/useRouteNavigation.ts
Labels: refactor

#146 [FEATURE] timetable context 생성
  src/App.tsx
  src/context/TimetableContext.ts
  src/infrastructure/impleStorageRepository.ts
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/DeleteDialog.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/pages/Main/Drawer/index.tsx
  src/pages/Main/TimeTable/index.tsx
  src/pages/Main/index.tsx
  src/usecases/timeTableService.ts
Labels: feature

#148 [REFACTOR] 삼항연산자 정리
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
Labels: refactor

#153 [FEATURE] 다크모드 구현하기
  src/App.tsx
  src/context/ColorSchemeContext.ts
  src/context/ServiceContext.ts
  src/infrastructure/impleStorageRepository.ts
  src/pages/MyPage/ColorScheme/index.tsx
  src/usecases/colorSchemeService.ts
  tailwind.config.js
Labels: feature

#155 [STYLE] 다크모드 노가다
  src/components/BottomeSheetContainer.tsx
  src/components/Loading.tsx
  src/components/Navbar.tsx
  src/components/common/HeaderContainer.tsx
  src/components/styles/WhiteButtonBox.tsx
  src/pages/Lecture/LectureDetail/index.tsx
  src/pages/Lecture/LectureList/index.tsx
  src/pages/Main/Drawer/AddTimeTableBottomSheet/index.tsx
  src/pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/pages/Main/Drawer/index.tsx
  src/pages/Main/Header/index.tsx
  src/pages/Main/TimeTable/index.tsx
  src/pages/MyPage/Account/ChangeNickname/index.tsx
  src/pages/MyPage/Account/index.tsx
  src/pages/MyPage/ColorScheme/index.tsx
  src/pages/MyPage/index.tsx
Labels: style

#159 [STYLE] 네비바 아래 마진 대신 패딩으로 수정
  src/components/Navbar.tsx
Labels: bug, style

#160 [FEAT] SPA to Next.js
  .gitignore
  next.config.mjs
  package.json
  src/App.tsx
  src/app/[[...slug]]/client.tsx
  src/app/[[...slug]]/page.tsx
  src/app/layout.tsx
  src/app_pages/Error/index.tsx
  src/app_pages/Landing/index.tsx
  src/app_pages/Lecture/CreateLecture/.keep
  src/app_pages/Lecture/LectureDetail/DeleteLectureDialog.tsx
  src/app_pages/Lecture/LectureDetail/index.tsx
  src/app_pages/Lecture/LectureList/index.tsx
  src/app_pages/Main/Drawer/AddTimeTableBottomSheet/index.tsx
  src/app_pages/Main/Drawer/AddTimeTableBySemesterBottomSheet/index.tsx
  src/app_pages/Main/Drawer/TimeTableMenuBottomSheet/ChangeNameDialog.tsx
  src/app_pages/Main/Drawer/TimeTableMenuBottomSheet/DeleteDialog.tsx
  src/app_pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/app_pages/Main/Drawer/index.tsx
  src/app_pages/Main/Header/index.tsx
  src/app_pages/Main/TimeTable/index.tsx
  src/app_pages/Main/index.tsx
  src/app_pages/MyPage/Account/ChangeNickname/index.tsx
  src/app_pages/MyPage/Account/index.tsx
  src/app_pages/MyPage/ColorScheme/index.tsx
  src/app_pages/MyPage/index.tsx
  src/app_pages/SignIn/index.tsx
  src/app_pages/SignUp/index.tsx
  src/context/EnvContext.ts
  src/main.tsx
  src/pages/Lecture/LectureList/.keep
  tsconfig.json
  yarn.lock
Labels: feature

#166 [FEAT] Next.js를 위한 eslint 설정 추가
  eslint.config.js
  package.json
  src/app_pages/Landing/index.tsx
  src/app_pages/Lecture/LectureDetail/index.tsx
  src/app_pages/Main/Drawer/index.tsx
  src/app_pages/Main/Header/index.tsx
  src/app_pages/SignIn/index.tsx
  src/components/Navbar.tsx
  yarn.lock
Labels: feature

#168 [FIX] Icon 공통 컨테이너 추가
  next.config.mjs
  src/app_pages/Landing/index.tsx
  src/app_pages/Lecture/LectureDetail/index.tsx
  src/app_pages/Main/Drawer/index.tsx
  src/app_pages/Main/Header/index.tsx
  src/app_pages/SignIn/index.tsx
  src/components/Navbar.tsx
  src/components/common/IconContainer.tsx
Labels: bug

#172 [STYLE] 슬랙에 올라온 수정사항들 반영
  src/app_pages/Lecture/LectureList/index.tsx
Labels: style

#176 [FIX] colorScheme localstorage issue 해결
  src/app_pages/MyPage/ColorScheme/index.tsx
Labels: bug

#173 [FIX] 무한로딩 에러 수정 및 recent timetable 삭제 이후 변경된 시간표에서 선택 버튼 나타나지 않는 오류 수정
  src/App.tsx
  src/app_pages/Main/Drawer/TimeTableMenuBottomSheet/DeleteDialog.tsx
  src/app_pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/app_pages/Main/Drawer/index.tsx
  src/app_pages/Main/TimeTable/index.tsx
  src/app_pages/Main/index.tsx
  src/components/common/HeaderContainer.tsx
  src/context/TimetableContext.ts
  src/infrastructure/impleStorageRepository.ts
  src/usecases/timeTableService.ts
Labels: bug

#178 [FEAT] 색상 보기 기능 추가
  src/app_pages/Lecture/LectureDetail/index.tsx
Labels: bug

#181 [FIX] 코드 수정 이후 css 깨지는 에러 수정
  src/App.tsx
  src/app/layout.tsx
Labels: bug

#182 [STYLE] 다크모드 수정
  src/app_pages/Main/Drawer/AddTimeTableBottomSheet/index.tsx
  src/app_pages/Main/Drawer/AddTimeTableBySemesterBottomSheet/index.tsx
Labels: style

#174 [FEAT] Custom 강의 직접생성 기능
  public/header/plus.svg
  src/App.tsx
  src/api/apis/api.ts
  src/api/apis/schemas.ts
  src/app_pages/Lecture/CreateLecture/.keep
  src/app_pages/Lecture/CreateLecture/ColorDropdown.tsx
  src/app_pages/Lecture/CreateLecture/ForceLectureDialog.tsx
  src/app_pages/Lecture/CreateLecture/TimeInput.tsx
  src/app_pages/Lecture/CreateLecture/index.tsx
  src/app_pages/Lecture/LectureDetail/index.tsx
  src/app_pages/Lecture/LectureList/index.tsx
  src/app_pages/Main/Drawer/AddTimeTableBottomSheet/index.tsx
  src/app_pages/Main/Drawer/AddTimeTableBySemesterBottomSheet/index.tsx
  src/app_pages/Main/Drawer/TimeTableMenuBottomSheet/index.tsx
  src/app_pages/Main/TimeTable/index.tsx
  src/components/BottomeSheetContainer.tsx
  src/constants/fileSource.ts
  src/entities/color.ts
  src/entities/error.ts
  src/entities/lecture.ts
  src/entities/time.ts
  src/infrastructure/impleLecutreRepository.ts
  src/usecases/lectureService.ts
  tailwind.config.js
Labels: feature

#184 [FIX] 강의 목록 리스트 바텀 네비바 선택된 메뉴 변경
  src/app_pages/Lecture/LectureList/index.tsx
Labels: bug

#186 [FIX] 불필요한 useEffect 제거
  src/app_pages/Main/index.tsx
Labels: bug
